name: Blue-Green EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            set -e
            if [ ! -d "/home/ubuntu/attendance-app/.git" ]; then
              # First-time setup
              mkdir -p /home/ubuntu/attendance-app
              git clone https://github.com/sufian-sani/student-app.git /home/ubuntu/attendance-app
            else
              # Subsequent deployments
              cd /home/ubuntu/attendance-app
              git pull origin main
            fi

            cd /home/ubuntu/attendance-app
            git pull origin main

            if docker ps | grep app_blue; then
              LIVE=blue
              IDLE=green
              LIVE_PORT=5001
              IDLE_PORT=5002
            else
              LIVE=green
              IDLE=blue
              LIVE_PORT=5002
              IDLE_PORT=5001
            fi

            echo "Live=$LIVE â†’ Deploying=$IDLE"

            docker compose up -d --build app_$IDLE
            sleep 15

            curl -f http://localhost:$IDLE_PORT || exit 1

            sudo sed -i "s/$LIVE_PORT/$IDLE_PORT/g" /etc/nginx/conf.d/attendance.conf
            sudo nginx -s reload

            docker stop app_$LIVE
